name: Tests

on:
  push:
    branches:
      - "**"
  workflow_call:

jobs:
  execute-tests:
    runs-on: ubuntu-latest
    container:
      image: fincenfetch/workflows:php-8.4
      credentials:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PAT }}

    steps:
      - uses: actions/checkout@v4

      - name: Cache composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ github.sha }}
          restore-keys: |
            ${{ github.sha }}

      - name: Install composer dependencies
        run: composer install --prefer-dist --ignore-platform-req=ext-gmp

      - name: Run test suite
        run: php vendor/bin/phpunit
